language: julia
os:
  - osx
  - linux
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("Wavelets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
